version: '3.8'
services:
  taskapi:
    container_name: taskapi-mediporta
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development